version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - database-volume:/app/instance
    environment:
      FLASK_ENV: development
      FLASK_APP: app.app  # Указываем путь к приложению

volumes:
  database-volume: